"""add key

Revision ID: d545838ccdbf
Revises: f4bbdc7fd4e4
Create Date: 2025-10-01 12:19:54.079835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd545838ccdbf'
down_revision: Union[str, Sequence[str], None] = 'f4bbdc7fd4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chapters', 'volumes', ['volume_id'], ['id'])
    op.create_foreign_key(None, 'volumes', 'novels', ['novel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volumes', type_='foreignkey')
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    # ### end Alembic commands ###
