"""index

Revision ID: d7fc7087b17d
Revises: faeae5a1649d
Create Date: 2025-10-05 21:28:24.502044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'd7fc7087b17d'
down_revision: Union[str, Sequence[str], None] = 'faeae5a1649d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookmarks_chapter_id'), 'bookmarks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_created_at'), 'bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookmarks_novel_id'), 'bookmarks', ['novel_id'], unique=False)
    op.create_index('ix_bookmarks_user_created', 'bookmarks', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_index('ix_bookmarks_user_novel', 'bookmarks', ['user_id', 'novel_id'], unique=True)
    op.create_index(op.f('ix_chapters_volume_id'), 'chapters', ['volume_id'], unique=False)
    op.create_index('ix_chapters_volume_order', 'chapters', ['volume_id', 'order'], unique=False)
    op.create_index(op.f('ix_histories_chapter_id'), 'histories', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_histories_created_at'), 'histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_histories_novel_id'), 'histories', ['novel_id'], unique=False)
    op.create_index('ix_histories_user_created', 'histories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_histories_user_id'), 'histories', ['user_id'], unique=False)
    op.create_index('ix_histories_user_novel', 'histories', ['user_id', 'novel_id'], unique=False)
    op.add_column('novels', sa.Column('full_text', sa.String(), nullable=True))
    op.add_column('novels', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    op.add_column('novels', sa.Column('latest_chapter_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_novels_title'), table_name='novels')
    op.create_index(op.f('ix_novels_average_rating'), 'novels', ['average_rating'], unique=False)
    op.create_index(op.f('ix_novels_created_at'), 'novels', ['created_at'], unique=False)
    op.create_index('ix_novels_created_desc', 'novels', [sa.literal_column('last_updated DESC')], unique=False)
    op.create_index(op.f('ix_novels_last_updated'), 'novels', ['last_updated'], unique=False)
    op.create_index(op.f('ix_novels_latest_chapter_id'), 'novels', ['latest_chapter_id'], unique=False)
    op.create_index(op.f('ix_novels_status'), 'novels', ['status'], unique=False)
    op.create_index('ix_novels_status_views', 'novels', ['status', 'total_views'], unique=False)
    op.create_index(op.f('ix_novels_total_favorites'), 'novels', ['total_favorites'], unique=False)
    op.create_index(op.f('ix_novels_total_views'), 'novels', ['total_views'], unique=False)
    op.create_index(op.f('ix_novels_type'), 'novels', ['type'], unique=False)
    op.create_index('ix_novels_type_rating', 'novels', ['type', 'average_rating'], unique=False)
    op.create_unique_constraint(None, 'novels', ['title'])
    op.create_foreign_key(None, 'novels', 'chapters', ['latest_chapter_id'], ['id'])
    op.create_index(op.f('ix_ratings_created_at'), 'ratings', ['created_at'], unique=False)
    op.create_index('ix_ratings_novel_created', 'ratings', ['novel_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ratings_novel_id'), 'ratings', ['novel_id'], unique=False)
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=False)
    op.create_index('ix_ratings_user_novel', 'ratings', ['user_id', 'novel_id'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_index('ix_view_stats_chapter_date', 'view_stats', ['chapter_id', 'date'], unique=True)
    op.create_index(op.f('ix_view_stats_chapter_id'), 'view_stats', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_view_stats_date'), 'view_stats', ['date'], unique=False)
    op.create_index('ix_view_stats_novel_date', 'view_stats', ['novel_id', 'date'], unique=False)
    op.create_index(op.f('ix_view_stats_novel_id'), 'view_stats', ['novel_id'], unique=False)
    op.create_index(op.f('ix_volumes_novel_id'), 'volumes', ['novel_id'], unique=False)
    op.create_index('ix_volumes_novel_order', 'volumes', ['novel_id', 'order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_volumes_novel_order', table_name='volumes')
    op.drop_index(op.f('ix_volumes_novel_id'), table_name='volumes')
    op.drop_index(op.f('ix_view_stats_novel_id'), table_name='view_stats')
    op.drop_index('ix_view_stats_novel_date', table_name='view_stats')
    op.drop_index(op.f('ix_view_stats_date'), table_name='view_stats')
    op.drop_index(op.f('ix_view_stats_chapter_id'), table_name='view_stats')
    op.drop_index('ix_view_stats_chapter_date', table_name='view_stats')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_ratings_user_novel', table_name='ratings')
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_novel_id'), table_name='ratings')
    op.drop_index('ix_ratings_novel_created', table_name='ratings')
    op.drop_index(op.f('ix_ratings_created_at'), table_name='ratings')
    op.drop_constraint(None, 'novels', type_='foreignkey')
    op.drop_constraint(None, 'novels', type_='unique')
    op.drop_index('ix_novels_type_rating', table_name='novels')
    op.drop_index(op.f('ix_novels_type'), table_name='novels')
    op.drop_index(op.f('ix_novels_total_views'), table_name='novels')
    op.drop_index(op.f('ix_novels_total_favorites'), table_name='novels')
    op.drop_index('ix_novels_status_views', table_name='novels')
    op.drop_index(op.f('ix_novels_status'), table_name='novels')
    op.drop_index(op.f('ix_novels_latest_chapter_id'), table_name='novels')
    op.drop_index(op.f('ix_novels_last_updated'), table_name='novels')
    op.drop_index('ix_novels_created_desc', table_name='novels')
    op.drop_index(op.f('ix_novels_created_at'), table_name='novels')
    op.drop_index(op.f('ix_novels_average_rating'), table_name='novels')
    op.create_index(op.f('ix_novels_title'), 'novels', ['title'], unique=True)
    op.drop_column('novels', 'latest_chapter_id')
    op.drop_column('novels', 'embedding')
    op.drop_column('novels', 'full_text')
    op.drop_index('ix_histories_user_novel', table_name='histories')
    op.drop_index(op.f('ix_histories_user_id'), table_name='histories')
    op.drop_index('ix_histories_user_created', table_name='histories')
    op.drop_index(op.f('ix_histories_novel_id'), table_name='histories')
    op.drop_index(op.f('ix_histories_created_at'), table_name='histories')
    op.drop_index(op.f('ix_histories_chapter_id'), table_name='histories')
    op.drop_index('ix_chapters_volume_order', table_name='chapters')
    op.drop_index(op.f('ix_chapters_volume_id'), table_name='chapters')
    op.drop_index('ix_bookmarks_user_novel', table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index('ix_bookmarks_user_created', table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_novel_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_created_at'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_chapter_id'), table_name='bookmarks')
    # ### end Alembic commands ###
