"""add time

Revision ID: f4bbdc7fd4e4
Revises: c76710fff3f9
Create Date: 2025-10-01 00:04:25.152599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4bbdc7fd4e4'
down_revision: Union[str, Sequence[str], None] = 'c76710fff3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('novels', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('volumes', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volumes', 'last_updated')
    op.drop_column('novels', 'last_updated')
    op.drop_column('chapters', 'last_updated')
    # ### end Alembic commands ###
