"""new fields

Revision ID: faeae5a1649d
Revises: 0676cd6e0212
Create Date: 2025-10-05 01:52:11.823834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faeae5a1649d'
down_revision: Union[str, Sequence[str], None] = '0676cd6e0212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('total_views', sa.Integer(), nullable=True))
    op.add_column('novels', sa.Column('total_views', sa.Integer(), nullable=True))
    op.add_column('novels', sa.Column('total_favorites', sa.Integer(), nullable=True))
    op.add_column('novels', sa.Column('total_ratings', sa.Integer(), nullable=True))
    op.add_column('novels', sa.Column('average_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novels', 'average_rating')
    op.drop_column('novels', 'total_ratings')
    op.drop_column('novels', 'total_favorites')
    op.drop_column('novels', 'total_views')
    op.drop_column('chapters', 'total_views')
    # ### end Alembic commands ###
