export interface Novel {
  id: number
  title: string
  author: string
  rating: number
  chapters: number
  views: number
  genres: string[]
  status: "Đang tiến hành" | "Hoàn thành" | "Tạm dừng"
  description: string
  coverImage: string
  isFeatured?: boolean
  isHot?: boolean
  isNew?: boolean
  lastUpdate?: string
  latestChapter?: string
}

export const mockNovels: Novel[] = [
  {
    id: 1,
    title: "Tái Sinh Thành Ma Vương Mạnh Nhất",
    author: "Takahashi Yuki",
    rating: 4.8,
    chapters: 342,
    views: 2500000,
    genres: ["Isekai", "Fantasy", "Action"],
    status: "Đang tiến hành",
    description:
      "Sau khi chết trong một tai nạn, tôi tái sinh thành ma vương mạnh nhất trong thế giới khác. Liệu tôi có thể sống một cuộc sống bình yên?",
    coverImage: "https://placewaifu.com/image/300/450",
    isFeatured: true,
    isHot: true,
    lastUpdate: "2 giờ trước",
    latestChapter: "Chapter 342: Trận Chiến Cuối Cùng",
  },
  {
    id: 2,
    title: "Nữ Hiệp Sĩ Và Phép Thuật Cổ Đại",
    author: "Sakura Mei",
    rating: 4.6,
    chapters: 256,
    views: 1800000,
    genres: ["Fantasy", "Romance", "Adventure"],
    status: "Đang tiến hành",
    description:
      "Câu chuyện về một nữ hiệp sĩ trẻ khám phá ra sức mạnh của phép thuật cổ đại và hành trình tìm kiếm sự thật về quá khứ của mình.",
    coverImage: "https://placewaifu.com/image/300/451",
    isFeatured: true,
    isNew: true,
    lastUpdate: "5 giờ trước",
    latestChapter: "Chapter 256: Bí Mật Được Tiết Lộ",
  },
  {
    id: 3,
    title: "Học Viện Phép Thuật: Sinh Viên Vô Danh",
    author: "Yamamoto Kenji",
    rating: 4.9,
    chapters: 428,
    views: 3200000,
    genres: ["Fantasy", "School Life", "Action"],
    status: "Đang tiến hành",
    description:
      "Một sinh viên bình thường tại học viện phép thuật danh giá nhất thế giới, nhưng ẩn chứa sức mạnh không ai ngờ tới.",
    coverImage: "https://placewaifu.com/image/300/452",
    isFeatured: true,
    isHot: true,
    lastUpdate: "1 giờ trước",
    latestChapter: "Chapter 428: Kỳ Thi Cuối Năm",
  },
  {
    id: 4,
    title: "Chuyển Sinh Thành Slime Tối Thượng",
    author: "Tanaka Hiroshi",
    rating: 4.7,
    chapters: 389,
    views: 2800000,
    genres: ["Isekai", "Comedy", "Fantasy"],
    status: "Đang tiến hành",
    description:
      "Tái sinh thành một con slime yếu ớt, nhưng với khả năng đặc biệt, tôi dần trở thành sinh vật mạnh nhất.",
    coverImage: "https://placewaifu.com/image/300/453",
    isFeatured: true,
    lastUpdate: "3 giờ trước",
    latestChapter: "Chapter 389: Liên Minh Mới",
  },
  {
    id: 5,
    title: "Kiếm Sĩ Huyền Thoại Trở Lại",
    author: "Sato Akira",
    rating: 4.5,
    chapters: 312,
    views: 2100000,
    genres: ["Action", "Fantasy", "Drama"],
    status: "Đang tiến hành",
    description: "Sau 100 năm bị phong ấn, kiếm sĩ huyền thoại thức tỉnh trong một thế giới hoàn toàn mới.",
    coverImage: "https://placewaifu.com/image/300/454",
    isFeatured: true,
    isNew: true,
    lastUpdate: "4 giờ trước",
    latestChapter: "Chapter 312: Thức Tỉnh",
  },
  {
    id: 6,
    title: "Công Chúa Băng Giá Và Hoàng Tử Lửa",
    author: "Nakamura Yui",
    rating: 4.4,
    chapters: 198,
    views: 1500000,
    genres: ["Romance", "Fantasy", "Drama"],
    status: "Đang tiến hành",
    description: "Hai vương quốc đối địch, hai người mang sức mạnh trái ngược, một tình yêu không thể nào.",
    coverImage: "https://placewaifu.com/image/240/360",
    isHot: true,
    lastUpdate: "6 giờ trước",
    latestChapter: "Chapter 198: Cuộc Gặp Gỡ Định Mệnh",
  },
  {
    id: 7,
    title: "Game Thủ Trong Thế Giới Thực",
    author: "Kobayashi Ren",
    rating: 4.6,
    chapters: 275,
    views: 2300000,
    genres: ["Action", "Game", "Adventure"],
    status: "Đang tiến hành",
    description: "Thế giới thực trở thành một game khổng lồ, và tôi là người duy nhất biết cách chơi.",
    coverImage: "https://placewaifu.com/image/240/361",
    isHot: true,
    isNew: true,
    lastUpdate: "7 giờ trước",
    latestChapter: "Chapter 275: Boss Raid",
  },
  {
    id: 8,
    title: "Thợ Săn Quỷ Dữ Cuối Cùng",
    author: "Watanabe Kaito",
    rating: 4.8,
    chapters: 456,
    views: 3500000,
    genres: ["Action", "Horror", "Fantasy"],
    status: "Đang tiến hành",
    description: "Trong thế giới bị quỷ dữ thống trị, một thợ săn đơn độc mang theo hy vọng cuối cùng của nhân loại.",
    coverImage: "https://placewaifu.com/image/240/362",
    isHot: true,
    lastUpdate: "8 giờ trước",
    latestChapter: "Chapter 456: Cuộc Chiến Sinh Tử",
  },
  {
    id: 9,
    title: "Tiểu Thư Quý Tộc Và Kỵ Sĩ Hộ Vệ",
    author: "Fujimoto Hana",
    rating: 4.3,
    chapters: 167,
    views: 1200000,
    genres: ["Romance", "Drama", "Slice of Life"],
    status: "Đang tiến hành",
    description: "Một tiểu thư quý tộc và người kỵ sĩ hộ vệ của cô, câu chuyện tình yêu vượt qua mọi rào cản giai cấp.",
    coverImage: "https://placewaifu.com/image/240/363",
    lastUpdate: "9 giờ trước",
    latestChapter: "Chapter 167: Lời Thú Nhận",
  },
  {
    id: 10,
    title: "Đế Chế Ma Thuật: Kẻ Nổi Loạn",
    author: "Ishikawa Daichi",
    rating: 4.7,
    chapters: 334,
    views: 2600000,
    genres: ["Fantasy", "Action", "Drama"],
    status: "Đang tiến hành",
    description: "Một phù thủy trẻ nổi loạn chống lại đế chế ma thuật độc tài để mang lại tự do cho mọi người.",
    coverImage: "https://placewaifu.com/image/240/364",
    isHot: true,
    lastUpdate: "10 giờ trước",
    latestChapter: "Chapter 334: Cuộc Nổi Dậy",
  },
  {
    id: 11,
    title: "Thế Giới Song Song: Hai Số Phận",
    author: "Matsumoto Aoi",
    rating: 4.5,
    chapters: 223,
    views: 1700000,
    genres: ["Isekai", "Mystery", "Romance"],
    status: "Đang tiến hành",
    description: "Sống trong hai thế giới song song, hai phiên bản của chính mình, một số phận được định sẵn.",
    coverImage: "https://placewaifu.com/image/240/365",
    isNew: true,
    lastUpdate: "11 giờ trước",
    latestChapter: "Chapter 223: Gặp Gỡ Chính Mình",
  },
  {
    id: 12,
    title: "Ninja Học Đường Hiện Đại",
    author: "Ito Haruki",
    rating: 4.4,
    chapters: 189,
    views: 1400000,
    genres: ["Action", "School Life", "Comedy"],
    status: "Đang tiến hành",
    description: "Một ninja thời hiện đại phải ẩn mình trong trường học bình thường, nhưng rắc rối cứ tìm đến.",
    coverImage: "https://placewaifu.com/image/240/366",
    lastUpdate: "12 giờ trước",
    latestChapter: "Chapter 189: Nhiệm Vụ Bí Mật",
  },
  {
    id: 13,
    title: "Pháp Sư Thời Gian Và Không Gian",
    author: "Kimura Sora",
    rating: 4.9,
    chapters: 401,
    views: 3100000,
    genres: ["Fantasy", "Adventure", "Mystery"],
    status: "Đang tiến hành",
    description:
      "Với khả năng điều khiển thời gian và không gian, một pháp sư trẻ phải ngăn chặn sự hủy diệt của vũ trụ.",
    coverImage: "https://placewaifu.com/image/240/367",
    isHot: true,
    lastUpdate: "1 ngày trước",
    latestChapter: "Chapter 401: Vết Nứt Thời Gian",
  },
  {
    id: 14,
    title: "Idol Và Người Hâm Mộ Bí Ẩn",
    author: "Suzuki Rina",
    rating: 4.2,
    chapters: 145,
    views: 980000,
    genres: ["Romance", "Slice of Life", "Drama"],
    status: "Đang tiến hành",
    description: "Một idol nổi tiếng và người hâm mộ bí ẩn của cô, câu chuyện tình yêu đầy bất ngờ.",
    coverImage: "https://placewaifu.com/image/240/368",
    lastUpdate: "1 ngày trước",
    latestChapter: "Chapter 145: Bí Mật Được Tiết Lộ",
  },
  {
    id: 15,
    title: "Chiến Binh Rồng Cuối Cùng",
    author: "Takeda Ryu",
    rating: 4.6,
    chapters: 367,
    views: 2400000,
    genres: ["Fantasy", "Action", "Adventure"],
    status: "Đang tiến hành",
    description: "Chiến binh cuối cùng có khả năng biến thành rồng, bảo vệ thế giới khỏi thế lực hắc ám.",
    coverImage: "https://placewaifu.com/image/240/369",
    isHot: true,
    lastUpdate: "1 ngày trước",
    latestChapter: "Chapter 367: Sức Mạnh Rồng",
  },
  {
    id: 16,
    title: "Thám Tử Siêu Nhiên",
    author: "Hayashi Kei",
    rating: 4.5,
    chapters: 234,
    views: 1900000,
    genres: ["Mystery", "Supernatural", "Drama"],
    status: "Đang tiến hành",
    description: "Một thám tử với khả năng nhìn thấy linh hồn giải quyết những vụ án bí ẩn nhất.",
    coverImage: "https://placewaifu.com/image/240/370",
    lastUpdate: "1 ngày trước",
    latestChapter: "Chapter 234: Vụ Án Bí Ẩn",
  },
  {
    id: 17,
    title: "Nữ Hoàng Băng Giá Của Học Viện",
    author: "Mori Yuki",
    rating: 4.3,
    chapters: 178,
    views: 1300000,
    genres: ["Romance", "School Life", "Comedy"],
    status: "Đang tiến hành",
    description: "Cô gái lạnh lùng nhất trường dần mở lòng với một chàng trai bình thường.",
    coverImage: "https://placewaifu.com/image/240/371",
    isNew: true,
    lastUpdate: "2 ngày trước",
    latestChapter: "Chapter 178: Trái Tim Tan Chảy",
  },
  {
    id: 18,
    title: "Hệ Thống Cấp Độ Vô Hạn",
    author: "Ono Takeshi",
    rating: 4.8,
    chapters: 445,
    views: 3300000,
    genres: ["Action", "Game", "Isekai"],
    status: "Đang tiến hành",
    description: "Với hệ thống cấp độ không giới hạn, tôi trở thành người mạnh nhất trong thế giới này.",
    coverImage: "https://placewaifu.com/image/240/372",
    isHot: true,
    lastUpdate: "2 ngày trước",
    latestChapter: "Chapter 445: Vượt Qua Giới Hạn",
  },
  {
    id: 19,
    title: "Tiệm Cà Phê Phép Thuật",
    author: "Kato Miku",
    rating: 4.1,
    chapters: 123,
    views: 850000,
    genres: ["Slice of Life", "Fantasy", "Comedy"],
    status: "Đang tiến hành",
    description: "Một tiệm cà phê bình thường, nhưng mỗi tách cà phê đều chứa đựng một phép màu nhỏ.",
    coverImage: "https://placewaifu.com/image/240/373",
    lastUpdate: "2 ngày trước",
    latestChapter: "Chapter 123: Khách Hàng Đặc Biệt",
  },
  {
    id: 20,
    title: "Võ Sĩ Vô Địch Thế Giới Khác",
    author: "Nishimura Ken",
    rating: 4.7,
    chapters: 389,
    views: 2700000,
    genres: ["Isekai", "Action", "Adventure"],
    status: "Đang tiến hành",
    description:
      "Một võ sĩ MMA chuyển sinh sang thế giới khác, sử dụng kỹ năng chiến đấu hiện đại để trở thành huyền thoại.",
    coverImage: "https://placewaifu.com/image/240/374",
    isHot: true,
    lastUpdate: "2 ngày trước",
    latestChapter: "Chapter 389: Giải Đấu Võ Thuật",
  },
  {
    id: 21,
    title: "Công Chúa Yêu Tinh Và Hiệp Sĩ Người",
    author: "Aoki Sakura",
    rating: 4.4,
    chapters: 267,
    views: 2000000,
    genres: ["Fantasy", "Romance", "Adventure"],
    status: "Hoàn thành",
    description: "Tình yêu giữa hai chủng tộc, vượt qua mọi định kiến và thù hận.",
    coverImage: "https://placewaifu.com/image/240/375",
    lastUpdate: "3 ngày trước",
    latestChapter: "Chapter 267: Kết Thúc Có Hậu",
  },
  {
    id: 22,
    title: "Đội Quân Bất Tử",
    author: "Ueda Shin",
    rating: 4.6,
    chapters: 312,
    views: 2200000,
    genres: ["Action", "Fantasy", "Horror"],
    status: "Đang tiến hành",
    description: "Một đội quân được ban cho sự bất tử, nhưng đó là phước hay họa?",
    coverImage: "https://placewaifu.com/image/240/376",
    lastUpdate: "3 ngày trước",
    latestChapter: "Chapter 312: Lời Nguyền Bất Tử",
  },
  {
    id: 23,
    title: "Học Viện Anh Hùng: Kẻ Yếu Nhất",
    author: "Saito Yuta",
    rating: 4.5,
    chapters: 289,
    views: 2100000,
    genres: ["Action", "School Life", "Drama"],
    status: "Đang tiến hành",
    description: "Sinh viên yếu nhất học viện anh hùng, nhưng ẩn chứa tiềm năng vô hạn.",
    coverImage: "https://placewaifu.com/image/240/377",
    isNew: true,
    lastUpdate: "3 ngày trước",
    latestChapter: "Chapter 289: Thức Tỉnh Sức Mạnh",
  },
  {
    id: 24,
    title: "Nữ Thần Chiến Tranh Tái Sinh",
    author: "Endo Rei",
    rating: 4.8,
    chapters: 423,
    views: 3000000,
    genres: ["Fantasy", "Action", "Romance"],
    status: "Đang tiến hành",
    description: "Nữ thần chiến tranh tái sinh trong thân phận một cô gái bình thường, tìm lại sức mạnh và ký ức.",
    coverImage: "https://placewaifu.com/image/240/378",
    isHot: true,
    lastUpdate: "4 ngày trước",
    latestChapter: "Chapter 423: Ký Ức Quá Khứ",
  },
  {
    id: 25,
    title: "Thế Giới Ảo Trở Thành Hiện Thực",
    author: "Goto Haruto",
    rating: 4.4,
    chapters: 234,
    views: 1800000,
    genres: ["Game", "Action", "Adventure"],
    status: "Đang tiến hành",
    description: "Game online yêu thích đột nhiên trở thành hiện thực, và tôi vẫn giữ được nhân vật của mình.",
    coverImage: "https://placewaifu.com/image/240/379",
    lastUpdate: "4 ngày trước",
    latestChapter: "Chapter 234: Thế Giới Mới",
  },
  {
    id: 26,
    title: "Ma Pháp Sư Tối Thượng",
    author: "Inoue Kaede",
    rating: 4.7,
    chapters: 378,
    views: 2500000,
    genres: ["Fantasy", "Action", "Drama"],
    status: "Đang tiến hành",
    description: "Hành trình từ một học viên ma pháp yếu ớt trở thành ma pháp sư mạnh nhất lịch sử.",
    coverImage: "https://placewaifu.com/image/240/380",
    isHot: true,
    lastUpdate: "4 ngày trước",
    latestChapter: "Chapter 378: Đỉnh Cao Ma Pháp",
  },
  {
    id: 27,
    title: "Cô Gái Có Thể Nhìn Thấy Tương Lai",
    author: "Tanaka Nana",
    rating: 4.3,
    chapters: 156,
    views: 1100000,
    genres: ["Mystery", "Romance", "Supernatural"],
    status: "Đang tiến hành",
    description: "Với khả năng nhìn thấy tương lai, cô gái cố gắng thay đổi số phận của những người xung quanh.",
    coverImage: "https://placewaifu.com/image/240/381",
    lastUpdate: "5 ngày trước",
    latestChapter: "Chapter 156: Thay Đổi Số Phận",
  },
  {
    id: 28,
    title: "Hiệp Sĩ Bóng Tối",
    author: "Yamada Riku",
    rating: 4.6,
    chapters: 345,
    views: 2300000,
    genres: ["Action", "Fantasy", "Drama"],
    status: "Đang tiến hành",
    description: "Một hiệp sĩ sử dụng sức mạnh bóng tối để bảo vệ ánh sáng.",
    coverImage: "https://placewaifu.com/image/240/382",
    lastUpdate: "5 ngày trước",
    latestChapter: "Chapter 345: Sức Mạnh Bóng Tối",
  },
  {
    id: 29,
    title: "Tiệm Sách Phép Thuật",
    author: "Nakano Hiro",
    rating: 4.2,
    chapters: 134,
    views: 920000,
    genres: ["Slice of Life", "Fantasy", "Mystery"],
    status: "Đang tiến hành",
    description: "Một tiệm sách cổ nơi mỗi cuốn sách đều chứa đựng một câu chuyện phép thuật thực sự.",
    coverImage: "https://placewaifu.com/image/240/383",
    lastUpdate: "5 ngày trước",
    latestChapter: "Chapter 134: Cuốn Sách Bị Nguyền Rủa",
  },
  {
    id: 30,
    title: "Vua Quỷ Và Công Chúa Thánh",
    author: "Okada Yui",
    rating: 4.5,
    chapters: 298,
    views: 2100000,
    genres: ["Fantasy", "Romance", "Action"],
    status: "Đang tiến hành",
    description: "Kẻ thù truyền kiếp, nhưng số phận đã đưa họ đến với nhau.",
    coverImage: "https://placewaifu.com/image/240/384",
    isNew: true,
    lastUpdate: "6 ngày trước",
    latestChapter: "Chapter 298: Tình Yêu Cấm Kỵ",
  },
]

export const categories = [
  { name: "Action", count: 156, gradient: "from-red-500 to-orange-500" },
  { name: "Romance", count: 234, gradient: "from-pink-500 to-rose-500" },
  { name: "Fantasy", count: 312, gradient: "from-purple-500 to-indigo-500" },
  { name: "Isekai", count: 189, gradient: "from-blue-500 to-cyan-500" },
  { name: "Comedy", count: 145, gradient: "from-yellow-500 to-amber-500" },
  { name: "Drama", count: 198, gradient: "from-indigo-500 to-purple-500" },
  { name: "Slice of Life", count: 123, gradient: "from-green-500 to-emerald-500" },
  { name: "Mystery", count: 167, gradient: "from-slate-500 to-gray-500" },
]
